spring:  h2:    console:      enabled: true
      path: /console
  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
    #data:    #- classpath:data.sql
  jpa:
    hibernate:      ddl-auto: create-drop    show-sql: true
    properties:      hibernate:
        format_sql: trugoogle:  recaptcha:    siteverify-url: https://www.google.com/recaptcha/api/siteverify    site-key: 6Ldjm7MZAAAAAHlk0bRd-fOcmrzNBTobDCNu_Zlb    secret-key: 6Ldjm7MZAAAAAG9XaTyb5Kvbdt7QK0apVFlBpjmH    naver:  login:    client-id: cSRUUkHUeBP4q5HJB5cw    client-secret: UTUxqhxAiy    callback-url: http://localhost:8080/naver/callback